----------------------------------------------------------------------------------------------------

throw 42

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Throw>
    <Integer value="42"/>
</Throw>

----------------------------------------------------------------------------------------------------

try {
    _
} catch {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <Id name="null"/>
    </Catch>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} finally {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <finally>
        <Id name="null"/>
    </finally>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch exc {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <Id name="exc"/>
        <Id name="null"/>
    </Catch>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch exc:Exception {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <TypeAssignment name="exc">
            <TypeId id="Exception"/>
        </TypeAssignment>
        <Id name="null"/>
    </Catch>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch exc:Exception {
    _
} catch exc:OtherException {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <TypeAssignment name="exc">
            <TypeId id="Exception"/>
        </TypeAssignment>
        <Id name="null"/>
    </Catch>
    <Catch>
        <TypeAssignment name="exc">
            <TypeId id="OtherException"/>
        </TypeAssignment>
        <Id name="null"/>
    </Catch>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch {
    1
} catch {
    2
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <Integer value="1"/>
    </Catch>
    <Catch>
        <Integer value="2"/>
    </Catch>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch {
    _
} finally {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <Id name="null"/>
    </Catch>
    <finally>
        <Id name="null"/>
    </finally>
</Try>

----------------------------------------------------------------------------------------------------

try {
    _
} catch {
    _
} catch {
    _
} finally {
    _
}

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

<Try>
    <Id name="null"/>
    <Catch>
        <Id name="null"/>
    </Catch>
    <Catch>
        <Id name="null"/>
    </Catch>
    <finally>
        <Id name="null"/>
    </finally>
</Try>

----------------------------------------------------------------------------------------------------
